apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance
        image: insurance:latest
